baseURL = ""
languageCode = "en"
title = "stats103"
disableKinds = [ "taxonomy", "taxonomyTerm" ]
publishDir = "docs"
theme = "tufteish"
relativeURLs = true

[author]
	name = "vaabe"

[params]
	description = "introductory course in probability, statistics, and regression"

[markup]
	defaultMarkdownHandler = "goldmark"
	[markup.goldmark]
		[markup.goldmark.extensions]
			definitionList = true
			footnote = true
			linkify = true
			strikethrough = true
			table = true
			taskList = true
			typographer = true
		[markup.goldmark.parser]
			attribute = true
			autoHeadingID = true
			autoHeadingIDType = "github"
		[markup.goldmark.renderer]
			hardWraps = false
			unsafe = false
			xhtml = false
	[markup.tableOfContents]
		    startLevel = 2
		    endLevel = 3
		    ordered = false

[permalinks]
	pages = "/:title/"
	pt1 = "/:title/"
	pt2 = "/:title/"
	pt3 = "/:title/"
	pt4 = "/:title/"
	pt5 = "/:title/"
