---
title: 'about'
output:
  tufte::tufte_html:
    tufte_features: ['fonts','background']
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = FALSE)
library(tidyverse)
library(knitr)
library(gridExtra)
library(extraDistr)
library(moments)
library(latex2exp)
library(rsconnect)
library(tufte)
```

---

The notes posted on this website are supplements to STAT-UB 103, an introductory course in modern statistical methods for analysis and model building. For demonstrations we've used R, a popular choice of programming language for statistical work (but one among many). The first three chapters are a pithy introduction to the R environment.  

Feedback is most welcome--please get in touch or submit a pull request on <a href="https://github.com/vaabe/stats103">Github</a>.   

More information on the course can be found in the <a href="./downloads/syllabus.pdf" download>syllabus</a>. 

Listed below are further textbooks/references we recommend--these are all free and have many examples and practice questions for your perusal. 

Introductory texts on statistical analysis:

- <a href="https://www.openintro.org/stat/textbook.php">OpenIntro Statistics</a>
- <a href="https://openstax.org/details/books/introductory-statistics">Openstax Introductory Statistics</a>

Slightly advanced texts with more on the modern stuff (model selection, ML, etc):

- <a href="http://www.statlearning.com/">Introduction to Statistical Learning</a>
- <a href="https://web.stanford.edu/~hastie/ElemStatLearn/">Elements of Statistical Learning</a> 

Detailed guides on using the R language:

- <a href="https://rstudio.cloud/learn/primers">RStudio Primers</a> (interactive)
- <a href="https://moderndive.com/">ModernDive</a>
- <a href="https://r4ds.had.co.nz/">R for Data Science</a>
- <a href="http://adv-r.had.co.nz/">Advanced R</a>


\ 

---

*Vinu Abeywick 2019*. Powered by <a href="https://pages.github.com/">Github Pages</a>, <a href="https://rmarkdown.rstudio.com/">R Markdown</a>, and <a href="https://github.com/edwardtufte/tufte-css">Tufte CSS</a>.  




















