---
title: 'stats103'
output:
  tufte::tufte_html:
    tufte_features: ['fonts','background','italics']
    css: 'mytufte.css'
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = FALSE)
library(tidyverse)
library(knitr)
library(gridExtra)
library(extraDistr)
library(moments)
library(latex2exp)
library(tufte)
```

\newcommand{\E}{\text{E}}
\newcommand{\Var}{\text{Var}}
\newcommand{\SD}{\text{SD}}
\newcommand{\SE}{\text{SE}}
\newcommand{\Cov}{\text{Cov}}
\newcommand{\Cor}{\text{Cor}}
\renewcommand{\P}{\text{P}}
\newcommand{\pd}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\sumin}{\sum_i^n}
\newcommand{\Bias}{\text{Bias}}

\newcommand{\head}[2]{\text{#1} \hspace{0.5cm} \text{#2}}

--- 

<a href="./about.html">about</a>  
<a href="./problemsets.html">problem sets</a>  
<a href="./datasets.html">data</a>  
<a href="./addenda.html">addenda</a>

### PART I --- ELEMENTS

- chapter 1 -- <a href="./notes/c1-R.html">The R Environment</a>
- chapter 2 -- <a href="./notes/c2-data-basics.html">Getting Started with Data</a></li>
- chapter 3 -- <a href="./notes/c3-wrangle-visualize.html">Wrangling and Visualizing Data</a></li>
- chapter 4 -- <a href="./notes/c4-basic-analysis.html">Basic Data Analayis</a></li>
- chapter 5 -- <a href="./notes/c5-basic-modeling.html">Basic Data Modeling</a></li>

### PART I $\frac 12$ --- A PROBABILISTIC BRIDGE

- chapter 7 -- <a href="./notes/c7-probability-elements.html">Elements of Probability</a>
- chapter 8 -- <a href="./notes/c8-random-variables.html">The Algebra of Random Variables</a>
- chapter 9 -- <a href="./notes/c9-probability-distributions.html">Distributions of Random Variables</a>   

### PART II --- VARIABILITY

- chapter 10 -- <a href="./notes/c10-sampling.html">Samples, Sampling, and Variability</a></li>
- chapter 11 -- <a href="./notes/c11-clt.html">The Central Limit Theorem</a></li>
- chapter 12 -- <a href="./notes/c12-intervals.html">Intervals</a></li>
- chapter 13 -- <a href="./notes/c13-testing-significance.html">Testing Significance</a></li>
- chapter 14 -- <a href="./notes/c14-joint-variability.html">Joint Variability</a></li>
- chapter 15 -- <a href="./notes/c15-regression-theory.html">A Little Regression Theory</a></li>
- chapter 16 -- <a href="./notes/c16-regression-inference-I.html">Inference from Regression Models, Part I</a></li>

### PART III -- BIAS

- chapter 17 -- <a href="./notes/c17-validity-bias.html">Validity and Bias</a></li>
- chapter 18 -- <a href="./notes/c18-error-of-an-estimator.html">Quantifying the Error of an Estimator</a></li>
- chapter 19 -- <a href="./notes/c19-regression-inference-II.html">Inference from Regression Models, Part II</a></li>
- chapter 20 -- <a href="./notes/c20-causal-inference.html">Causal Inference</a></li>
- chapter 21 -- <a href="./notes/c21-bias-variance.html">Model Selection \& The Bias-Variance Tradeoff</a></li>

### PART IV -- FURTHER TOPICS

- chapter 22 -- Classification with Logistic Regression
- chapter 23 -- Time Series
- chapter 24 -- Maximum Likelihood  

\ 

\ 



