---
title: "ps4"
author: "whomsoever"
---
---
title: "ps4"
author: "whomsoever"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gapminder)
library(ggfortify)
library(fivethirtyeight)
```

\ 

# Estimator Bias 

```{r}
## generate a random sample
n = 15
data = sample(1:6, n, replace = TRUE)
```

\ 

```{r}
## a function that calculates sample variance
## but using n in the denominator instead of n-1 (population formula)
varn = function(x) mean((x - mean(x))^2)
```

\ 

```{r}
## two estimates of variance

# use the R function (uses the n-1 denominator)
var(data)

# use the population formula  
varn(data)
```

\ 

```{r}
## repeat the experiment and find the expected value of each estimator

# sample formula
mean(replicate(10000, var(sample(1:6, n, replace = TRUE))))

# population formula 
mean(replicate(10000, varn(sample(1:6, n, replace = TRUE))))
```

\ 

```{r}
## repeat the experiment and find the standard deviation value of each estimator

# sample formula
sd(replicate(10000, var(sample(1:6, n, replace = TRUE))))

# population formula 
sd(replicate(10000, varn(sample(1:6, n, replace = TRUE))))
```



\ 

# Confounding Variables 

```{r}
## read in funding data 
funding = read.csv("https://stats103.org/data/funding-bias.csv")
funding = read.csv("../data/funding-bias.csv")

```

\ 

```{r}
## two-sample t test for mean funding between regional groups
t.test(funding ~ origin, data = funding)
```

\ 

```{r}
## simple regression
reg1 = lm(funding ~ origin, data = funding)
summary(reg1)
```

\ 

```{r}
## multiple regression
reg2 = lm(funding ~ origin + gender + age, data = funding)
summary(reg2)
```





\ 

# Log Models

```{r}
## use data from 2007
gm2007 = gapminder %>% filter(year == "2007")
```

\ 

```{r}
## linear model predicting life expectancy from GDP per capita
reg3 = lm(lifeExp ~ gdpPercap, data = gm2007)
summary(reg3)
```

\ 

```{r}
## diagnostic plots
autoplot(reg3)
```

\ 

```{r}
## scatterplot of life expectancy on GDP per capita
ggplot(data = gm2007, aes(x = gdpPercap, y = lifeExp)) + geom_point()
```

\ 

```{r}
## scatterplot of life expectancy on log GDP per capita
ggplot(data = gm2007, aes(x = log(gdpPercap), y = lifeExp)) + geom_point()
```

\ 

```{r}
## linear model predicting life expectancy from log GDP per capita
reg4 = lm(lifeExp ~ log(gdpPercap), data = gm2007)
summary(reg4)
```

\ 

# Logistic Regression 

```{r}
## logistic model with two predictors
mod1 = glm(won_primary ~ percentage_endorsement_points + percentage_of_money,
             family = binomial, data = endorsements)
summary(mod1)
```

\ 

```{r}
## exponentiate coefficients
exp(coef(mod1))
```

\ 

```{r}
## more complex logistic model that includes party and interaction terms
mod2 = glm(won_primary ~ percentage_endorsement_points : party +
               percentage_of_money : party +
               percentage_endorsement_points * percentage_of_money,
             family = binomial, data = endorsements)
summary(mod2)
```

\ 

```{r}
## compare interaction model to simpler model
anova(mod1, mod2, test = "LRT")
```

\ 

```{r}
ends = endorsements %>%
  mutate(yhat = predict(mod1, type = "response"),
         predicted_win = yhat > mean(won_primary))

ggplot(ends, aes(x = percentage_of_money, y = percentage_endorsement_points,
                 color = yhat,shape = won_primary)) +
  geom_point(alpha = .8)
```

\ 

```{r}
ends %>% group_by(won_primary, predicted_win) %>%
  summarize(count = n())

table(ends$won_primary, ends$predicted_win)
```

\ 




